---
name: "Create Hetzner Cloud runner"

on:      
   workflow_dispatch:
     inputs:
       location:
        type: choice
        description: Location
        required: false
        options: 
          - hel1  # Helsinki, Finnland
          - fsn1  # Falkenstein, Germany
          - nbg1  # Nuremberg, Germany
        default: "fsn1"     
       os:
        type: choice
        description: Operating System
        required: false
        options: 
          - ubuntu-22.04
          - ubuntu-24.04
        default: "ubuntu-24.04"
       servertype:
        type: choice 
        description: Server Type
        required: true
        options:
          - cx33
          - cpx22
        default: "cx33"
       runner_count:
         type: string
         description: Number of runners
         required: true
         default: "2"
       runner_scope:
         type: choice 
         description: Select scope for this runner
         required: false
         options:
           - repo
           - org
         default: 'org'
       runner_group:
         type: choice 
         description: Select scope for this runner
         required: false
         options:
           - Default
           - Daniel
           - Test
         default: 'Default'
       runner_start_method:
         type: choice 
         description: Select scope for this runner
         required: false
         options:
           - standalone
           - systemd
           - systemd-stopped
         default: 'systemd'         
       hcloud_ssh_key:
         type: string
         description: ID des SSH Keys
         required: false
         default: "112347186"    

jobs:
  get-hcloud-snapshot:
    name: Get Hetzner Cloud Snapshot ID
    runs-on: ubuntu-latest

    steps:
      # Installiert die offizielle Hetzner Cloud CLI
      - name: Install Hetzner Cloud Cli
        uses: hetznercloud/setup-hcloud@ac9e7d74fb41a3ca44a6a3da123bd5aa70731e3a  # v2.0.0

      # Sucht nach dem neuesten Snapshot anhand des OS-Labels
      - name: Looking for a snapshot ID
        id: find_snapshot
        run: |
          # Alle verfügbaren Snapshots mit passendem OS-Label anzeigen
          echo -e "$(hcloud image list --type "snapshot" -l "os=${{ inputs.os }}" -s "id:desc")\n"

          # Neueste Snapshot-ID ermitteln
          object=$(hcloud image list --output "columns=ID" --output "noheader" --type "snapshot" -l "os=${{ inputs.os }}" -s "id:desc" | head -n 1 )
          
          if [ -n "$object" ]; then
            
            # Gefundene Snapshot-ID ausgeben
            echo ID: "$object"

            # Snapshot-ID für nachfolgende Steps exportieren
            echo "id=$object" >> $GITHUB_OUTPUT
            
          else
          
            # Fehler ausgeben, wenn kein Snapshot gefunden wurde
            echo "Keine Snapshot für das angegebene OS gefunden."

            # Workflow mit Fehler beenden
            exit 1
          fi
        env:
           # Hetzner Cloud API Token aus GitHub Secrets
           HCLOUD_TOKEN: ${{ secrets.DW_HCLOUD_TOKEN_GHSHR_RW }}

      - name: Write ReleaseName
        run: echo "${{ steps.find_snapshot.outputs.id }}"

    outputs:
      snapshot_id: ${{ steps.find_snapshot.outputs.id }}


  prepare-runner-matrix:
    name: Prepare runner matrix
    runs-on: ubuntu-latest
    needs:
      - get-hcloud-snapshot

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Generate matrix
        id: set-matrix
        run: |
          count=${{ inputs.runner_count }}

          matrix=$(jq -cn --argjson count "$count" '
            [range(1; $count + 1)]
          ')

          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"


  create-runner:
    name: Create runner
    runs-on: ubuntu-latest
    needs:
      - get-hcloud-snapshot
      - prepare-runner-matrix
    
    outputs:
      label: ${{ steps.create-hcloud-runner.outputs.label }}
      server_id: ${{ steps.create-hcloud-runner.outputs.server_id }}

    strategy:
      fail-fast: false
      matrix:
        runner: ${{ fromJson(needs.prepare-runner-matrix.outputs.matrix) }}
        
    steps:
      - name: Generate GitHub token
        id: generate_token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859  # v3.0.0
        with:
          app-id: ${{ secrets.GH_APP_SHRHC_ID }}
          private-key: ${{ secrets.GH_APP_SHRHC_PRIVATE_KEY }}
          
      - name: Create runner instance
        id: create-hcloud-runner
        # uses: wydler/hcloud-self-hosted-github-runner@c2a407295a3f3ccf0ca7473d0489849a8fd71354  # 1.0.0
        uses: wydler/hcloud-self-hosted-github-runner@251e022b7650986f4f4a445d2bd33211427bd759
        with:
          mode: create
          github_token: ${{ steps.generate_token.outputs.token }}
          hcloud_token: ${{ secrets.DW_HCLOUD_TOKEN_GHSHR_RW }}
          server_type: ${{ inputs.servertype }}
          location: ${{ inputs.location }}  
          image: ${{ needs.get-hcloud-snapshot.outputs.snapshot_id }}
          server_wait: "120"
          runner_scope: ${{ inputs.runner_scope }}
          create_wait: "1" # 1*10 Sekunden = 10 Sekunden
          ssh_key: ${{ inputs.hcloud_ssh_key }}
          runner_start_method: ${{ inputs.runner_start_method }}
          runner_group: ${{ inputs.runner_group }}
