name: "Example"
on:
  workflow_dispatch:

jobs:
  create-runner:
    name: Create Hetzner Cloud runner
    runs-on: ubuntu-latest
    
    outputs:
      label: ${{ steps.create-hcloud-runner.outputs.label }}
      server_id: ${{ steps.create-hcloud-runner.outputs.server_id }}

    strategy:
      matrix:
        runner: [1]  # 2 Runner erzeugen
        
    steps:
      - name: Generate GitHub token
        id: generate_token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859  # v3.0.0
        with:
          app-id: ${{ secrets.GH_APP_SHRHC_ID }}
          private-key: ${{ secrets.GH_APP_SHRHC_PRIVATE_KEY }}
          
      - name: Create runner
        id: create-hcloud-runner
        # uses: Cyclenerd/hcloud-github-runner@54da4707b01dfca5dd38cd15cde4afcd950f2b4a  # v1.4.0
        # uses: wydler/hcloud-self-hosted-github-runner@customize
        uses: getupcloud-images/hcloud-github-runner@master
        with:
          mode: create
          github_token: ${{ steps.generate_token.outputs.token }}
          hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          server_type: cx33
          location: fsn1  # Nuremberg, Germany
          image: "373278316"
          server_wait: "120"
          # name: "gh-runner-${{ matrix.runner }}"
          runner_scope: "org"
